spring.application.name=commission_backend

server.port=8484

#Database config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/commission_db
spring.datasource.username=root
spring.datasource.password=1234

# application.properties
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#spring.jpa.hibernate.ddl-auto=create